spring:
  application:
    name: questioncloud
  datasource:
    url: jdbc:mysql://localhost:3306/questioncloud_db?serverTimezone=Asia/Shanghai
    username: root
    password: 861007889
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: sk-b3c6fffb6266416abbc611c80ba79e3b
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3s

server:
  port: 8080

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

file:
  storage:
    # 本地存储配置
    local:
      # 文件存储的基础路径。可以是绝对路径 (e.g., /var/files) 或相对路径 (e.g., uploads)。
      # 相对路径将以项目运行目录为基准。
      base-path: /Users/evmb/questioncloud-storage
    # 配额配置
    quota:
      # 是否启用配额检查
      enabled: true
      # 每个用户每周允许上传的文件数量
      files-per-week: 50
  upload:
    allowed-image-extensions:
      - jpg
      - jpeg
      - png
    allowed-doc-extensions:
      - doc
      - docx
      - pdf