package cn.sztu.questioncloud.application.knowledge_point.enums;

import lombok.Getter;

@Getter
public enum KnowledgeSubjectEnum {

    MATH(0, "MATH"),
    COMPUTER_SCIENCE(1, "COMPUTER_SCIENCE"),
    SOFTWARE_ENGINEERING(2, "SOFTWARE_ENGINEERING"),
    ARTIFICIAL_INTELLIGENCE(3, "ARTIFICIAL_INTELLIGENCE"),
    DATA_SCIENCE(4, "DATA_SCIENCE"),
    CYBER_SECURITY(5, "CYBER_SECURITY"),

    MEDICINE(6, "MEDICINE"),
    CLINICAL_MEDICINE(7, "CLINICAL_MEDICINE"),
    NURSING(8, "NURSING"),
    PHARMACY(9, "PHARMACY"),
    PUBLIC_HEALTH(10, "PUBLIC_HEALTH"),

    CIVIL_ENGINEERING(11, "CIVIL_ENGINEERING"),
    MECHANICAL_ENGINEERING(12, "MECHANICAL_ENGINEERING"),
    ELECTRONIC_ENGINEERING(13, "ELECTRONIC_ENGINEERING"),
    ELECTRICAL_ENGINEERING(14, "ELECTRICAL_ENGINEERING"),
    AUTOMATION(15, "AUTOMATION"),
    COMMUNICATION_ENGINEERING(16, "COMMUNICATION_ENGINEERING"),

    PHYSICS(17, "PHYSICS"),
    CHEMISTRY(18, "CHEMISTRY"),
    BIOLOGY(19, "BIOLOGY"),
    ENVIRONMENTAL_SCIENCE(20, "ENVIRONMENTAL_SCIENCE"),

    ECONOMICS(21, "ECONOMICS"),
    FINANCE(22, "FINANCE"),
    ACCOUNTING(23, "ACCOUNTING"),
    BUSINESS_ADMINISTRATION(24, "BUSINESS_ADMINISTRATION"),
    MANAGEMENT(25, "MANAGEMENT"),

    LAW(26, "LAW"),
    EDUCATION(27, "EDUCATION"),
    PSYCHOLOGY(28, "PSYCHOLOGY"),

    CHINESE_LANGUAGE_LITERATURE(29, "CHINESE_LANGUAGE_LITERATURE"),
    ENGLISH(30, "ENGLISH"),
    FOREIGN_LANGUAGE(31, "FOREIGN_LANGUAGE"),
    JOURNALISM_COMMUNICATION(32, "JOURNALISM_COMMUNICATION"),

    HISTORY(33, "HISTORY"),
    PHILOSOPHY(34, "PHILOSOPHY"),
    POLITICAL_SCIENCE(35, "POLITICAL_SCIENCE"),
    SOCIOLOGY(36, "SOCIOLOGY"),

    ART_DESIGN(37, "ART_DESIGN"),
    MUSIC(38, "MUSIC"),
    SPORTS_SCIENCE(39, "SPORTS_SCIENCE"),

    OTHER(99, "OTHER");

    private final Integer code;
    private final String description;

    KnowledgeSubjectEnum(Integer code, String description) {
        this.code = code;
        this.description = description;
    }
}